/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BasicXYColumnChart.java
 *
 * Created on 30.01.2010, 16:12:31
 */
package at.redeye.FrameWork.base.chart.impl;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Paint;
import org.apache.log4j.Logger;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.labels.StandardCategoryItemLabelGenerator;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.IntervalMarker;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.chart.renderer.category.CategoryItemRenderer;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.ui.Layer;

/**
 *
 * @author Mario
 */
public class BasicCategoryBarChart extends javax.swing.JPanel {

    private static Logger logger =
            Logger.getLogger(BasicCategoryBarChart.class.getSimpleName());
    private DefaultCategoryDataset dataset = null;
    private ChartPanel chartPanel = null;

    /** Creates new form BasicXYColumnChart */
    public BasicCategoryBarChart() {
        logger.error("Calling without args is not allowed. Use other constructor!");
    }

    public BasicCategoryBarChart(CategoryChartData data) {

        initComponents();
        dataset = data.getDataset();
        add(loadChart(data), BorderLayout.CENTER);

    }

    /**
     * A custom renderer that returns a different color for each item in a single series.
     */
    class CustomRenderer extends BarRenderer {

        /** The colors. */
        private Paint[] colors;

        /**
         * Creates a new renderer.
         *
         * @param colors  the colors.
         */
        public CustomRenderer(final Paint[] colors) {
            this.colors = colors;
        }

        /**
         * Returns the paint for an item.  Overrides the default behaviour inherited from
         * AbstractSeriesRenderer.
         *
         * @param row  the series.
         * @param column  the category.
         *
         * @return The item color.
         */
        @Override
        public Paint getItemPaint(final int row, final int column) {
            return this.colors[column % this.colors.length];
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    private ChartPanel loadChart(CategoryChartData data) {

        JFreeChart chart = createChart(data);
        chartPanel = new ChartPanel(chart);
        chartPanel.setPreferredSize(new java.awt.Dimension(500, 270));
        return chartPanel;

    }

    private final JFreeChart createChart(CategoryChartData data) {


        JFreeChart chart = ChartFactory.createBarChart(
                data.getTitleOfChart(),
                data.getxAxisName(),
                data.getyAxisName(),
                dataset,
                data.getOrientation(),
                true,
                true,
                false);

        chart.setBackgroundPaint(getBackground());
        CategoryPlot plot = (CategoryPlot) chart.getPlot();
        plot.setBackgroundPaint(getBackground());

        StandardCategoryItemLabelGenerator labgen = new StandardCategoryItemLabelGenerator();

        final CategoryItemRenderer catRenderer = new CustomRenderer(
                new Paint[]{Color.BLUE, Color.RED, Color.lightGray,
                    Color.green,
                    Color.yellow, Color.orange, Color.cyan,
                    Color.magenta});
        
        catRenderer.setBaseItemLabelGenerator(labgen);
        catRenderer.setBaseItemLabelsVisible(true);
        catRenderer.setBaseSeriesVisibleInLegend(false);
        plot.setRenderer(catRenderer);




        IntervalMarker target = data.getIntervalMarker();
        if (target != null) {
            plot.addRangeMarker(target, Layer.BACKGROUND);
        }
        return chart;
    }

    public void updateDataSet(CategoryChartData data) {

        dataset.clear();
        for (int rowidx = 0; rowidx < data.getDataset().getRowCount(); rowidx++) {
            for (int colidx = 0; colidx < data.getDataset().getColumnCount(); colidx++) {
                dataset.addValue(data.getDataset().getValue(rowidx, colidx),
                        data.getDataset().getRowKey(rowidx), data.getDataset().getColumnKey(colidx));

            }
        }
    }
}
