package at.redeye.FrameWork.base.bindtypes;

/**
 * Transient builder step produced by {@link Condition#where(DBValue)},
 * {@link Condition#and(DBValue)}, and {@link Condition#or(DBValue)}.
 *
 * <p>Holds the pending column reference until an operator method
 * ({@code eq}, {@code ne}, {@code gt}, etc.) is called, which adds a
 * {@link Condition.Term} to the owning {@link Condition} and returns it
 * so the chain can continue.</p>
 *
 * Generated by AI (GitHub Copilot / Claude Sonnet 4.6)
 */
public final class ConditionStep {

    private final Condition owner;
    private final DBValue column;
    private final boolean isAnd;   // true = AND combinator, false = OR

    /** Entry point: first term, combinator is irrelevant (ignored for term 0). */
    ConditionStep(Condition owner, DBValue column) {
        this(owner, column, true);
    }

    ConditionStep(Condition owner, DBValue column, boolean isAnd) {
        if (column == null) {
            throw new IllegalArgumentException(
                "column must not be null — pass a static final DBValue field");
        }
        this.owner  = owner;
        this.column = column;
        this.isAnd  = isAnd;
    }

    /** {@code col = ?} */
    public Condition eq(Object value)   { return owner.addTerm(column, "=",    value, isAnd); }

    /** {@code col <> ?} */
    public Condition ne(Object value)   { return owner.addTerm(column, "<>",   value, isAnd); }

    /** {@code col > ?} */
    public Condition gt(Object value)   { return owner.addTerm(column, ">",    value, isAnd); }

    /** {@code col < ?} */
    public Condition lt(Object value)   { return owner.addTerm(column, "<",    value, isAnd); }

    /** {@code col >= ?} */
    public Condition gte(Object value)  { return owner.addTerm(column, ">=",   value, isAnd); }

    /** {@code col <= ?} */
    public Condition lte(Object value)  { return owner.addTerm(column, "<=",   value, isAnd); }

    /** {@code col LIKE ?} */
    public Condition like(String value) { return owner.addTerm(column, "LIKE", value, isAnd); }

    /** {@code col IS NULL} — no bind parameter emitted */
    public Condition isNull()    { return owner.addNullTerm(column, true,  isAnd); }

    /** {@code col IS NOT NULL} — no bind parameter emitted */
    public Condition isNotNull() { return owner.addNullTerm(column, false, isAnd); }
}
