package at.redeye.FrameWork.base.bindtypes;

import at.redeye.SqlDBInterface.SqlDBIO.StmtCreatorInterface;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/**
 * Immutable (after building) typed WHERE-clause builder.
 *
 * <p>Build a condition by starting with the static factory and chaining operator
 * and combinator calls:</p>
 *
 * <pre>{@code
 * // single condition
 * Condition.where(OrderLine.ORDER_ID).eq(42)
 *
 * // AND chain
 * Condition.where(OrderLine.ORDER_ID).eq(orderId)
 *          .and(OrderLine.STATUS).eq("open")
 *
 * // OR
 * Condition.where(OrderLine.STATUS).eq("open")
 *          .or(OrderLine.STATUS).eq("pending")
 * }</pre>
 *
 * <p>Column references must be {@code static final DBValue} fields declared on the
 * target {@link DBStrukt} subclass.  Typos in the field name produce a compiler error
 * rather than a runtime failure.</p>
 *
 * <p>Values are bound via JDBC {@code ?} placeholders — never interpolated into SQL.</p>
 *
 * Generated by AI (GitHub Copilot / Claude Sonnet 4.6)
 */
public final class Condition {

    // -----------------------------------------------------------------------
    // Internal term representation
    // -----------------------------------------------------------------------

    /**
     * One comparison term: {@code table.column OP ?} or {@code table.column IS [NOT] NULL}.
     *
     * Generated by AI (GitHub Copilot / Claude Sonnet 4.6)
     */
    static final class Term {
        final DBValue column;
        final String  op;        // "=", "<>", ">", "<", ">=", "<=", "LIKE", "IS NULL", "IS NOT NULL"
        final Object  value;     // null for IS NULL / IS NOT NULL
        final boolean hasParam;  // false for IS NULL / IS NOT NULL
        final boolean isAnd;     // combinator with previous term (ignored for first term)

        Term(DBValue column, String op, Object value, boolean isAnd) {
            this.column   = column;
            this.op       = op;
            this.value    = value;
            this.hasParam = true;
            this.isAnd    = isAnd;
        }

        /** For IS NULL / IS NOT NULL — no bind parameter. */
        Term(DBValue column, boolean isNull, boolean isAnd) {
            this.column   = column;
            this.op       = isNull ? "IS NULL" : "IS NOT NULL";
            this.value    = null;
            this.hasParam = false;
            this.isAnd    = isAnd;
        }
    }

    // -----------------------------------------------------------------------
    // State
    // -----------------------------------------------------------------------

    private final List<Term> terms = new ArrayList<>();

    // -----------------------------------------------------------------------
    // Construction — package-private; only ConditionStep builds terms
    // -----------------------------------------------------------------------

    Condition() {}

    /** Called by {@link ConditionStep} for value-based operators. */
    Condition addTerm(DBValue column, String op, Object value, boolean isAnd) {
        terms.add(new Term(column, op, value, isAnd));
        return this;
    }

    /** Called by {@link ConditionStep} for IS NULL / IS NOT NULL. */
    Condition addNullTerm(DBValue column, boolean isNull, boolean isAnd) {
        terms.add(new Term(column, isNull, isAnd));
        return this;
    }

    // -----------------------------------------------------------------------
    // Entry point
    // -----------------------------------------------------------------------

    /**
     * Starts a new {@code Condition} with the first column reference.
     * The returned {@link ConditionStep} must be completed with an operator call
     * ({@code eq}, {@code gt}, {@code like}, {@code isNull}, …).
     *
     * @param column a {@code static final DBValue} field from the target DBStrukt subclass
     */
    public static ConditionStep where(DBValue column) {
        return new ConditionStep(new Condition(), column);
    }

    // -----------------------------------------------------------------------
    // Chaining
    // -----------------------------------------------------------------------

    /**
     * Appends the next column reference combined with AND.
     * Must be completed with an operator call.
     */
    public ConditionStep and(DBValue column) {
        return new ConditionStep(this, column, true);
    }

    /**
     * Appends the next column reference combined with OR.
     * Must be completed with an operator call.
     */
    public ConditionStep or(DBValue column) {
        return new ConditionStep(this, column, false);
    }

    // -----------------------------------------------------------------------
    // Rendering — called by Transaction, not by callers
    // -----------------------------------------------------------------------

    /**
     * Renders the full {@code WHERE} clause with {@code ?} placeholders.
     *
     * <p>Column names are quoted via {@link StmtCreatorInterface#markTableName} and
     * {@link StmtCreatorInterface#markColumnName} for correct dialect escaping.</p>
     *
     * @param creator   dialect-specific name quoter from the active executor
     * @param tableName the primary table name (from {@code DBStrukt.getName()})
     * @return complete WHERE clause, e.g. {@code WHERE "t"."col1" = ? AND "t"."col2" > ?},
     *         or empty string if no terms were added
     */
    public String renderWhere(StmtCreatorInterface creator, String tableName) {
        if (terms.isEmpty()) {
            return "";
        }

        String quotedTable = creator.markTableName(tableName);
        StringBuilder sb = new StringBuilder("WHERE ");

        for (int i = 0; i < terms.size(); i++) {
            Term t = terms.get(i);
            if (i > 0) {
                sb.append(t.isAnd ? " AND " : " OR ");
            }
            sb.append(quotedTable)
              .append('.')
              .append(creator.markColumnName(t.column.getName()))
              .append(' ')
              .append(t.op);
            if (t.hasParam) {
                sb.append(" ?");
            }
        }

        return sb.toString();
    }

    /**
     * Returns the bind values in the same order as the {@code ?} placeholders in
     * {@link #renderWhere}. IS NULL / IS NOT NULL terms contribute no entry.
     */
    public List<Object> getBindValues() {
        List<Object> values = new ArrayList<>(terms.size());
        for (Term t : terms) {
            if (t.hasParam) {
                values.add(t.value);
            }
        }
        return Collections.unmodifiableList(values);
    }
}
