package at.redeye.FrameWork.base.bindtypes;

/**
 * Referential action for ON DELETE / ON UPDATE clauses of a foreign key constraint.
 *
 * Generated by AI (GitHub Copilot / Claude Sonnet 4.6)
 */
public enum FKAction {

    /** Default: no automatic action taken; the DBMS rejects the operation if it
     *  would violate the constraint. */
    NO_ACTION,

    /** Automatically delete/update dependent rows when the referenced row is
     *  deleted/updated. */
    CASCADE,

    /** Set the FK column to NULL when the referenced row is deleted/updated.
     *  The FK column must be nullable for this to be valid DDL. */
    SET_NULL,

    /** Rejects the delete/update of a referenced row if dependent rows exist.
     *  Semantically similar to NO_ACTION but checked immediately (not deferred). */
    RESTRICT
}
