package at.redeye.FrameWork.base.bindtypes;

/**
 * Describes a single foreign key constraint that a {@link DBStrukt} column
 * has toward another table.
 *
 * <p>Instances are immutable. Use {@link #withName(String)} to obtain a copy
 * with an auto-generated constraint name filled in.</p>
 *
 * <p>If {@code name} is {@code null} when the instance is passed to
 * {@link DBStrukt#addForeignKey(ForeignKeyDefinition, int)}, the strukt will
 * call {@link #withName(String)} to set a name derived from the owning table
 * and column: {@code FK_<TABLE>_<COLUMN>} (uppercased).</p>
 *
 * Generated by AI (GitHub Copilot / Claude Sonnet 4.6)
 */
public class ForeignKeyDefinition {

    /** Constraint name used in ADD CONSTRAINT / DROP CONSTRAINT DDL statements. */
    private final String name;

    /** Column in the owning (child) table that holds the FK value. */
    private final String ownerColumn;

    /** Target (parent) table name (stored uppercased). */
    private final String referencedTable;

    /** Target (parent) column name. */
    private final String referencedColumn;

    /** Action taken when the referenced row is deleted. */
    private final FKAction onDelete;

    /** Action taken when the referenced row is updated. */
    private final FKAction onUpdate;

    // -----------------------------------------------------------------------
    // Constructors
    // -----------------------------------------------------------------------

    /**
     * Full constructor — all fields supplied explicitly.
     *
     * @param name             constraint name (may be {@code null}; auto-generated
     *                         by {@link DBStrukt#addForeignKey} in that case)
     * @param ownerColumn      FK column in the owning table
     * @param referencedTable  parent table
     * @param referencedColumn parent column
     * @param onDelete         referential action on DELETE
     * @param onUpdate         referential action on UPDATE
     */
    public ForeignKeyDefinition(String name,
                                String ownerColumn,
                                String referencedTable,
                                String referencedColumn,
                                FKAction onDelete,
                                FKAction onUpdate) {
        this.name             = name;
        this.ownerColumn      = ownerColumn;
        this.referencedTable  = referencedTable == null ? null : referencedTable.toUpperCase();
        this.referencedColumn = referencedColumn;
        this.onDelete         = onDelete  != null ? onDelete  : FKAction.NO_ACTION;
        this.onUpdate         = onUpdate  != null ? onUpdate  : FKAction.NO_ACTION;
    }

    /**
     * Convenience constructor — constraint name will be auto-generated by
     * {@link DBStrukt#addForeignKey}.
     */
    public ForeignKeyDefinition(String ownerColumn,
                                String referencedTable,
                                String referencedColumn,
                                FKAction onDelete,
                                FKAction onUpdate) {
        this(null, ownerColumn, referencedTable, referencedColumn, onDelete, onUpdate);
    }

    /**
     * Minimal constructor — {@code NO_ACTION} for both ON DELETE and ON UPDATE,
     * constraint name auto-generated.
     */
    public ForeignKeyDefinition(String ownerColumn,
                                String referencedTable,
                                String referencedColumn) {
        this(null, ownerColumn, referencedTable, referencedColumn,
             FKAction.NO_ACTION, FKAction.NO_ACTION);
    }

    // -----------------------------------------------------------------------
    // Accessors (read-only)
    // -----------------------------------------------------------------------

    /** Returns the constraint name, or {@code null} if not yet assigned. */
    public String getName()             { return name; }

    /** Column in the owning table that carries the FK value. */
    public String getOwnerColumn()      { return ownerColumn; }

    /** Parent table name (uppercased). */
    public String getReferencedTable()  { return referencedTable; }

    /** Parent column name. */
    public String getReferencedColumn() { return referencedColumn; }

    /** Referential action on DELETE. Never {@code null}. */
    public FKAction getOnDelete()       { return onDelete; }

    /** Referential action on UPDATE. Never {@code null}. */
    public FKAction getOnUpdate()       { return onUpdate; }

    // -----------------------------------------------------------------------
    // Immutable copy helpers
    // -----------------------------------------------------------------------

    /**
     * Returns a new {@code ForeignKeyDefinition} identical to this one except
     * with the given constraint name. Used by {@link DBStrukt#addForeignKey} to
     * attach an auto-generated name without mutating the original object.
     *
     * @param effectiveName the constraint name to use
     * @return a new instance with {@code name} set
     */
    public ForeignKeyDefinition withName(String effectiveName) {
        return new ForeignKeyDefinition(effectiveName, ownerColumn,
                referencedTable, referencedColumn, onDelete, onUpdate);
    }

    // -----------------------------------------------------------------------
    // Object overrides
    // -----------------------------------------------------------------------

    @Override
    public String toString() {
        return "ForeignKeyDefinition{"
                + "name='" + name + '\''
                + ", ownerColumn='" + ownerColumn + '\''
                + ", referencedTable='" + referencedTable + '\''
                + ", referencedColumn='" + referencedColumn + '\''
                + ", onDelete=" + onDelete
                + ", onUpdate=" + onUpdate
                + '}';
    }
}
