package at.redeye.FrameWork.base.bindtypes;

/**
 * Thrown when a requested FK relationship cannot be resolved from the
 * {@link DBStrukt}'s declared foreign key list.
 *
 * <p>Typical causes:</p>
 * <ul>
 *   <li>The column name passed to {@code fetchChildren} / {@code fetchParent}
 *       does not match any FK declared via {@link DBStrukt#addForeignKey}.</li>
 *   <li>The referenced table name does not match the parent strukt's table name.</li>
 * </ul>
 *
 * Generated by AI (GitHub Copilot / Claude Sonnet 4.6)
 */
public class ForeignKeyNotFoundException extends Exception {

    public ForeignKeyNotFoundException(String message) {
        super(message);
    }
}
