/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * WizardBaseWindow.java
 *
 * Created on 16.03.2010, 18:39:32
 */
package at.redeye.FrameWork.base.wizards.impl;

import at.redeye.FrameWork.base.BaseDialog;
import at.redeye.FrameWork.base.Root;
import at.redeye.FrameWork.base.wizards.WizardAction;
import at.redeye.FrameWork.base.wizards.WizardWindowInterface;
import java.util.HashMap;
import javax.swing.BorderFactory;

/**
 *
 * @author Mario
 */
public abstract class WizardBaseWindow extends BaseDialog implements WizardWindowInterface {

    private HashMap<WizardAction, Boolean> actionControl;
    private WizardAction action;
    

    /** Creates new form WizardBaseWindow */
    public WizardBaseWindow(Root root, String title) {
        super(root, title);
        actionControl = new HashMap<WizardAction, Boolean>();
        actionControl.put(WizardAction.WIZARD_ACTION_CLOSE, allowCloseBeforeEnd());
        actionControl.put(WizardAction.WIZARD_ACTION_NEXT, allowJumpNextWindow());
        actionControl.put(WizardAction.WIZARD_ACTION_PREV, allowJumpPrevWindow());
        actionControl.put(WizardAction.WIZARD_ACTION_FINISH, allowJumpToEnd());
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGuestContent = new javax.swing.JPanel();
        buttonCancel = new javax.swing.JButton();
        buttonPrev = new javax.swing.JButton();
        buttonNext = new javax.swing.JButton();
        buttonFinish = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaMenuTree = new javax.swing.JTextArea();
        labelLogoBig = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textAreaHelp = new javax.swing.JTextArea();
        textAreaHelp.setText(getHelptext());

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBounds(new java.awt.Rectangle(200, 200, 0, 0));
        setResizable(false);

        panelGuestContent.setMinimumSize(new java.awt.Dimension(300, 200));
        panelGuestContent.setLayout(new java.awt.BorderLayout());

        buttonCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/at/redeye/FrameWork/base/resources/icons/fileclose.gif"))); // NOI18N
        buttonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelActionPerformed(evt);
            }
        });

        buttonPrev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/at/redeye/FrameWork/base/resources/icons/prev.png"))); // NOI18N
        buttonPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPrevActionPerformed(evt);
            }
        });

        buttonNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/at/redeye/FrameWork/base/resources/icons/next.png"))); // NOI18N
        buttonNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNextActionPerformed(evt);
            }
        });

        buttonFinish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFinishActionPerformed(evt);
            }
        });

        textAreaMenuTree.setBackground(new java.awt.Color(240, 240, 240));
        textAreaMenuTree.setColumns(15);
        textAreaMenuTree.setEditable(false);
        textAreaMenuTree.setFont(new java.awt.Font("Courier New", 1, 14));
        textAreaMenuTree.setLineWrap(true);
        textAreaMenuTree.setRows(5);
        textAreaMenuTree.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(100, 150, 230), null));
        jScrollPane1.setViewportView(textAreaMenuTree);

        labelLogoBig.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelLogoBig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/at/redeye/FrameWork/base/resources/icons/icon.png"))); // NOI18N

        textAreaHelp.setBackground(new java.awt.Color(240, 240, 240));
        textAreaHelp.setColumns(20);
        textAreaHelp.setEditable(false);
        textAreaHelp.setFont(new java.awt.Font("Courier New", 1, 14));
        textAreaHelp.setLineWrap(true);
        textAreaHelp.setRows(4);
        textAreaHelp.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(100, 150, 230), null));
        jScrollPane2.setViewportView(textAreaHelp);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelLogoBig, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
                    .addComponent(panelGuestContent, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonNext, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonFinish, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelGuestContent, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelLogoBig, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buttonFinish, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonNext, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelActionPerformed
        action = WizardAction.WIZARD_ACTION_CLOSE;
        close();

    }//GEN-LAST:event_buttonCancelActionPerformed

    private void buttonPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPrevActionPerformed
        action = WizardAction.WIZARD_ACTION_PREV;
        getParentWizard().handleUpdate();
    }//GEN-LAST:event_buttonPrevActionPerformed

    private void buttonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNextActionPerformed
        action = WizardAction.WIZARD_ACTION_NEXT;
        getParentWizard().handleUpdate();

    }//GEN-LAST:event_buttonNextActionPerformed

    private void buttonFinishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFinishActionPerformed
        action = WizardAction.WIZARD_ACTION_FINISH;
    }//GEN-LAST:event_buttonFinishActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonFinish;
    private javax.swing.JButton buttonNext;
    private javax.swing.JButton buttonPrev;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelLogoBig;
    protected javax.swing.JPanel panelGuestContent;
    private javax.swing.JTextArea textAreaHelp;
    protected javax.swing.JTextArea textAreaMenuTree;
    // End of variables declaration//GEN-END:variables

    protected void setWindowTitle(String title) {
        this.setTitle(title);
    }

    protected void setButtonCancelText(String text) {
        System.out.println("Text cancel: " + text);
        buttonCancel.setText(text);
    }

    protected void setButtonFinishText(String text) {
        buttonFinish.setText(text);
    }

    protected void setButtonNextText(String text) {
        buttonNext.setText(text);
    }

    protected void setButtonPrevText(String text) {
        buttonPrev.setText(text);
    }

    protected void setAreaMenuTreeTitle(String text) {
        textAreaMenuTree.setBorder(BorderFactory.createTitledBorder(text));
    }

    protected void controlButtons() {

        buttonNext.setEnabled(actionControl.get(WizardAction.WIZARD_ACTION_NEXT));
        buttonPrev.setEnabled(actionControl.get(WizardAction.WIZARD_ACTION_PREV));
        buttonCancel.setEnabled(actionControl.get(WizardAction.WIZARD_ACTION_CLOSE));
        buttonFinish.setEnabled(actionControl.get(WizardAction.WIZARD_ACTION_FINISH));

    }

    protected abstract void setGuestContent();

    protected abstract String getHelptext();

    public WizardAction getRecentAction() {
        return action;
    }

    protected void applyActionRule (WizardAction action, boolean isGranted) {
        actionControl.remove(action);
        actionControl.put(action, isGranted);
    }
    
    protected abstract Wizard getParentWizard();

    @Override
    protected boolean openWithLastWidthAndHeight() {
        return false;
    }


}
