/*
 * ImageListContent.java
 *
 * Created on 24. Juni 2009, 21:15
 */

package at.redeye.FrameWork.base.imagestorage;

import at.redeye.FrameWork.base.imagestorage.bindtypes.DBImage;
import javax.swing.Icon;

/**
 *
 * @author  martin
 */
public class ImageListContent extends javax.swing.JPanel {

    /** Creates new form ImageListContent */
    int id = -1;
    
    public ImageListContent() {
        initComponents();
    }

    private ImageListContent(Icon icon, String toString) {
        initComponents();
        
        label.setText(toString);
        label.setIcon(icon);
    }
    
    public void setId(int id)
    {
        this.id = id;
    }
    
    public int getId()
    {
        return id;
    }
    
    public static ImageListContent createPanelFromDB(DBImage image) 
    {
        Icon icon = ImageUtils.loadScaledImageIcon(image.image.value,image.file_name.toString(),100,100);
        
        ImageListContent ilc = new ImageListContent(icon,image.file_name.toString());
        ilc.setId((Integer)image.id.getValue());
        return ilc;
    }
    
    public String getText()
    {
        return label.getText();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label = new javax.swing.JLabel();

        label.setText("Foobar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel label;
    // End of variables declaration//GEN-END:variables

}
