/*
 * ImageStorage.java
 *
 * Created on 11. Juni 2009, 11:43
 */

package at.redeye.FrameWork.base.imagestorage;

import at.redeye.FrameWork.base.AutoMBox;
import at.redeye.FrameWork.base.BaseDialog;
import at.redeye.FrameWork.base.CanCloseInterface;
import at.redeye.FrameWork.base.DefaultCanClose;
import at.redeye.FrameWork.base.FrameWorkConfigDefinitions;
import at.redeye.FrameWork.base.Root;
import at.redeye.FrameWork.base.imagestorage.bindtypes.DBImage;
import at.redeye.FrameWork.utilities.ReadFile;
import at.redeye.FrameWork.utilities.StringUtils;
import at.redeye.FrameWork.widgets.helpwindow.HelpWin;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author  martin
 */
public class ImageStorage extends BaseDialog implements CanCloseInterface {
                    
    private static RemovingAllowedInterface remover = null;
    private static String last_path = null;
    
    /** Creates new form ImageStorage */
    public ImageStorage(Root root) {
        super(root,"Bilderverwaltung");
        initComponents();
                
        imageList.setParent(this);
        
        feed_list();
    }
    
    public static void setRemovingAllowedHandler(RemovingAllowedInterface remover)
    {
        ImageStorage.remover = remover;
    }

    private void feed_list() 
    {
        imageList.feed_list();
    }

    @Override
    public boolean canClose()
    {
        return DefaultCanClose.DefaultCanClose(this);
    }
    
    public void saveData()
    {
        jBSaveActionPerformed(null);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        helpButton = new javax.swing.JButton();
        buttonClose = new javax.swing.JButton();
        jBDel = new javax.swing.JButton();
        jLTitle = new javax.swing.JLabel();
        jBSave = new javax.swing.JButton();
        jBLoad = new javax.swing.JButton();
        imageList = new at.redeye.FrameWork.base.imagestorage.ImageStoragePanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        helpButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/at/redeye/FrameWork/base/resources/icons/help.png"))); // NOI18N
        helpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpButtonActionPerformed(evt);
            }
        });

        buttonClose.setFont(new java.awt.Font("Tahoma", 0, 12));
        buttonClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/at/redeye/FrameWork/base/resources/icons/fileclose.gif"))); // NOI18N
        buttonClose.setText("Schließen");
        buttonClose.setPreferredSize(new java.awt.Dimension(130, 31));
        buttonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCloseActionPerformed(evt);
            }
        });

        jBDel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/at/redeye/FrameWork/base/resources/icons/edittrash.gif"))); // NOI18N
        jBDel.setText("Löschen");
        jBDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDelActionPerformed(evt);
            }
        });

        jLTitle.setFont(new java.awt.Font("Dialog", 1, 18));
        jLTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLTitle.setText("Bilderverwaltung");

        jBSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/at/redeye/FrameWork/base/resources/icons/button_ok.gif"))); // NOI18N
        jBSave.setText("Speichern");
        jBSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSaveActionPerformed(evt);
            }
        });

        jBLoad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/at/redeye/FrameWork/base/resources/icons/player_eject.png"))); // NOI18N
        jBLoad.setText("Laden");
        jBLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLoadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imageList, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(helpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBLoad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBDel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                        .addComponent(buttonClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(helpButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imageList, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBSave)
                    .addComponent(jBLoad)
                    .addComponent(jBDel))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void helpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpButtonActionPerformed
java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new HelpWin(root, "/at/redeye/UserManagement/resources/Help/", "EA Verwaltung").setVisible(true);
            }
        });
}//GEN-LAST:event_helpButtonActionPerformed

private void buttonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCloseActionPerformed
 
    new AutoMBox(getTitle()) {    
        @Override
        public void do_stuff() throws Exception {
            
            if( canClose() )
            {
                getTransaction().rollback();
                close();
            }
        }
    };
    
}//GEN-LAST:event_buttonCloseActionPerformed

private void jBDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDelActionPerformed
// TODO add your handling code here:
    final ImageListContent content = (ImageListContent) imageList.getSelectedValue();

    if( content == null )
        return;        
                
    new AutoMBox(getTitle()) {

        @Override
        public void do_stuff() throws Exception {
            
            if( remover.canRemoveImage(getTransaction(), content.getId() ) == false )
            {
                JOptionPane.showMessageDialog(null,
                        StringUtils.autoLineBreak(
                        "Diese Bild wird noch verwendet und darf daher nicht entfernt werden."),                        
                        "Error",
                        JOptionPane.OK_OPTION);
                return;
            }
            
            DBImage image = new DBImage();

            getTransaction().updateValues(
                    "delete from " +
                    getTransaction().markTable(image) +
                    " where " +
                    getTransaction().markColumn(image.id) +
                    " = '" + content.getId() + "'");
            imageList.removeValue(content);            
            setEdited();
        }
    };    

 
}//GEN-LAST:event_jBDelActionPerformed

private void jBSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSaveActionPerformed
     
    new AutoMBox(getTitle()) {

            @Override
            public void do_stuff() throws Exception {
                getTransaction().commit();
                clearEdited();
            }
        
    };
}//GEN-LAST:event_jBSaveActionPerformed

private void jBLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLoadActionPerformed
// TODO add your handling code here:
    
    JFileChooser fc = new JFileChooser();
    
    fc.setAcceptAllFileFilterUsed(false);
    fc.setFileFilter(new ImageFileFilter());
    fc.setMultiSelectionEnabled(true);    
    
    if( last_path != null )
    {
        fc.setCurrentDirectory(new File(last_path));
    }
    // is Arschlangsam daher mach ma das eher nicht.
    
    if( root.getSetup().getLocalConfig(FrameWorkConfigDefinitions.ImagePreviewInFileOpen).equalsIgnoreCase("true") )
    {
        fc.setFileView(new ImageFileView());
    }
    
    int retval = fc.showOpenDialog(this);
    
    if( retval != 0 )    
      return;
    
    final File[] files = fc.getSelectedFiles();        
    
    new AutoMBox(this.getTitle()) {

        @Override
        public void do_stuff() throws Exception {

            for (int i = 0; i < files.length; i++) {
                System.out.println("file: " + files[i].getName());
                last_path = files[i].getPath();
                
                final DBImage image = new DBImage();

                byte[] bytes = ReadFile.getBytesFromFile(files[i]);

                image.image.value = bytes;

                image.id.loadFromCopy(getNewSequenceValue(image.getName()));
                image.file_name.loadFromString(files[i].getName());
                image.hist.setAnHist(root.getUserName());

                getTransaction().insertValues(image);    
                setEdited();
                
                Thread t = new Thread() {

                    @Override
                    public void run() 
                    {
                        ImageListContent content = ImageListContent.createPanelFromDB(image);
                        imageList.addValue(content);                                             
                    }
                };

                t.start();
            }
        }
    };
         
}//GEN-LAST:event_jBLoadActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonClose;
    private javax.swing.JButton helpButton;
    private at.redeye.FrameWork.base.imagestorage.ImageStoragePanel imageList;
    private javax.swing.JButton jBDel;
    private javax.swing.JButton jBLoad;
    private javax.swing.JButton jBSave;
    private javax.swing.JLabel jLTitle;
    // End of variables declaration//GEN-END:variables

}
