/*
 * ImageStoragePanel.java
 *
 * Created on 24. Juni 2009, 23:21
 */

package at.redeye.FrameWork.base.imagestorage;

import java.util.List;
import java.util.Vector;

import at.redeye.FrameWork.base.AutoMBox;
import at.redeye.FrameWork.base.BaseDialog;
import at.redeye.FrameWork.base.bindtypes.DBStrukt;
import at.redeye.FrameWork.base.imagestorage.bindtypes.DBImage;

/**
 * 
 * @author martin
 */
public class ImageStoragePanel extends javax.swing.JPanel {

	Vector<ImageListContent> list = new Vector<ImageListContent>();
	BaseDialog parent = null;

	/** Creates new form ImageStoragePanel */
	public ImageStoragePanel(BaseDialog parent) {
		initComponents();

		this.parent = parent;
		imageList.setCellRenderer(new ImageCellRenderer());

		feed_list();
	}

	/** Creates new form ImageStoragePanel */
	public ImageStoragePanel() {
		initComponents();

		imageList.setCellRenderer(new ImageCellRenderer());
	}

	public void setParent(BaseDialog parent) {
		this.parent = parent;
	}

	public BaseDialog getBaseParent() {
		return this.parent;
	}

	public void clear() {
		list.clear();
	}

	public void feed_list() {
		new AutoMBox(parent.getTitle()) {

			@Override
			public void do_stuff() throws Exception {

				final List<DBStrukt> res = parent.getTransaction().fetchTable(
						new DBImage());

				list.clear();

				Thread t = new Thread() {

					@Override
					public void run() {

						for (int i = 0; i < res.size(); i++) {

							DBImage image = (DBImage) res.get(i);
							ImageListContent content = ImageListContent
									.createPanelFromDB(image);
							list.add(content);
							imageList.setListData(list);
						}
					}
				};
				t.start();
			}
		};
	}

	public Vector<ImageListContent> getList() {
		return list;
	}

	public ImageListContent getSelectedValue() {
		return (ImageListContent) imageList.getSelectedValue();
	}

	public void updateList() {
		imageList.setListData(list);
	}

	public void removeValue(ImageListContent content) {
		list.remove(content);
		updateList();
	}

	public void addValue(ImageListContent content) {
		list.add(content);
		updateList();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jScrollPane1 = new javax.swing.JScrollPane();
		imageList = new javax.swing.JList();

		imageList
				.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
		jScrollPane1.setViewportView(imageList);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING,
				javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300,
				Short.MAX_VALUE));
	}// </editor-fold>//GEN-END:initComponents

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JList imageList;
	private javax.swing.JScrollPane jScrollPane1;
	// End of variables declaration//GEN-END:variables

}
