/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package at.redeye.FrameWork.base.dbmanager.impl;

import at.redeye.FrameWork.base.bindtypes.DBStrukt;
import at.redeye.FrameWork.base.transaction.Transaction;
import at.redeye.SqlDBInterface.SqlDBIO.impl.ColumnAttribute;
import java.sql.SQLException;

/**
 *
 * @author martin
 */
public class CreateSqlMySql extends BaseCreateSql {
    /* nothing todo */        
    
    private Transaction trans;
    private String dbversion;
    int max_varchar_length = 255;
    
    public CreateSqlMySql( Transaction trans )
    {
        this.trans = trans;
    }
    
    public CreateSqlMySql()
    {
        
    }    
    
    @Override
    public String createSqlforTable( DBStrukt strukt )
    {
        if( trans != null ) {
            try {
                ShowTablesMySql show_tables = new ShowTablesMySql();
                dbversion = show_tables.getDBVersion(trans);
                
                if( show_tables.isVersionNewerThan(dbversion,5,0,3) ) {
                    max_varchar_length = 65535;
                }
                
            } catch( SQLException ex ) {
                logger.error(ex,ex);
                throw new RuntimeException(ex);
            }
        }
        
        return super.createSqlforTable(strukt);
    }
    
    @Override
    protected String addStorageInfo()
    {
        return " ENGINE='InnoDB' DEFAULT CHARSET='utf8' COLLATE='utf8_general_ci'";
    }

    @Override
    public String markColumn(String col) {

        return "`" + col + "`";
    }
    
    /**
     * MySQL uses DROP FOREIGN KEY, not DROP CONSTRAINT.
     * Generated by AI (GitHub Copilot / Claude Sonnet 4.6)
     */
    @Override
    protected String dropFKStatement( String table, String constraintName )
    {
        return "ALTER TABLE " + markColumn( table )
             + " DROP FOREIGN KEY " + markColumn( constraintName );
    }

    @Override
    protected String createSqlForRow( ColumnAttribute attr ) {
        
        switch( attr.getDatatype() )
        {
            case DB_TYPE_STRING:
                if( attr.getWidth() > max_varchar_length && !attr.isPrimaryKey() ) {
                    return "TEXT";
                }
                return "VARCHAR(" + attr.getWidth() + ")";
            case DB_TYPE_DATETIME: return "DATETIME";
            case DB_TYPE_DATE: return "DATE";            
            
            case DB_TYPE_FLOAT:
            case DB_TYPE_DOUBLE:
                return "double";
            
            case DB_TYPE_LONG:             
            case DB_TYPE_INTEGER:
            case DB_TYPE_BOOLEAN:
            case DB_TYPE_BIT:
            case DB_TYPE_SHORT:
                return "int";
                
            case DB_TYPE_BLOB:
                return "MEDIUMBLOB";
        }
        
        return null;
    }
}
