/*
 * RootWin.java
 *
 * Created on 10. November 2008, 23:19
 */

package at.redeye.FrameWork.base;

import org.apache.log4j.BasicConfigurator;

import at.redeye.FrameWork.base.ml.TableLang;

/**
 *
 * @author  martin
 */
public class RootWin extends BaseDialog {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/** Creates new form RootWin */
    public RootWin( Root root ) {
        super( root , "FrameWork" );
        initComponents();
        
        BasicConfigurator.configure();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        JMDatabase = new javax.swing.JMenuItem();
        JMQuit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        JMTableTest = new javax.swing.JMenuItem();
        JMBindDesc = new javax.swing.JMenuItem();
        JMLang = new javax.swing.JMenuItem();
        JMPmf = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jMenu1.setText("System");

        JMDatabase.setText("Datanbankverbindung");
        JMDatabase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMDatabaseActionPerformed(evt);
            }
        });
        jMenu1.add(JMDatabase);

        JMQuit.setText("Beenden");
        JMQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMQuitActionPerformed(evt);
            }
        });
        jMenu1.add(JMQuit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Menu");

        JMTableTest.setText("TableTest");
        JMTableTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMTableTestActionPerformed(evt);
            }
        });
        jMenu2.add(JMTableTest);

        JMBindDesc.setText("BindDesc");
        JMBindDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMBindDescActionPerformed(evt);
            }
        });
        jMenu2.add(JMBindDesc);

        JMLang.setText("Sprachen");
        JMLang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMLangActionPerformed(evt);
            }
        });
        jMenu2.add(JMLang);

        JMPmf.setText("PMF");
        JMPmf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMPmfActionPerformed(evt);
            }
        });
        jMenu2.add(JMPmf);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void JMDatabaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMDatabaseActionPerformed
// TODO add your handling code here:
     java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {                
                new ConnectionDialog( root ).setVisible( true );
            }
     });    
}//GEN-LAST:event_JMDatabaseActionPerformed

private void JMQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMQuitActionPerformed
// TODO add your handling code here:        
    close();
}//GEN-LAST:event_JMQuitActionPerformed

private void JMTableTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMTableTestActionPerformed
// TODO add your handling code here:
         java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {                
                //new TableTest( root ).setVisible( true );
            }
     });  
}//GEN-LAST:event_JMTableTestActionPerformed

private void JMBindDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMBindDescActionPerformed
// TODO add your handling code here:
    
     java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {                
                //new TableBindDesc( root ).setVisible( true );
            }
     });   
}//GEN-LAST:event_JMBindDescActionPerformed

private void JMLangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMLangActionPerformed
// TODO add your handling code here:
    
     java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {                
                new TableLang( root ).setVisible( true );
            }
     }); 
}//GEN-LAST:event_JMLangActionPerformed

private void JMPmfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMPmfActionPerformed
// TODO add your handling code here:
     java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {                
                //new TablePMF( root ).setVisible( true );
            }
     }); 
}//GEN-LAST:event_JMPmfActionPerformed

@Override
public void close()
{
    super.close();
    root.appExit();
    this.dispose();
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem JMBindDesc;
    private javax.swing.JMenuItem JMDatabase;
    private javax.swing.JMenuItem JMLang;
    private javax.swing.JMenuItem JMPmf;
    private javax.swing.JMenuItem JMQuit;
    private javax.swing.JMenuItem JMTableTest;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables

}
