/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * H1ConnectionManagerUI.java
 *
 * Created on 26.05.2009, 16:26:51
 */
package at.redeye.Communication.sps.H1.ui.impl;

import java.awt.event.KeyEvent;

import javax.swing.JOptionPane;

import org.apache.log4j.Logger;

import at.redeye.Communication.ConnectionPhase;
import at.redeye.Communication.sps.H1.comm.IH1CommListener;
import at.redeye.Communication.sps.H1.comm.IH1Communication;
import at.redeye.Communication.sps.H1.comm.IH1QueueSender;
import at.redeye.Communication.sps.H1.comm.impl.H1ConnectionDefinition;
import at.redeye.Communication.sps.H1.comm.impl.H1QueueSender;
import at.redeye.Communication.sps.H1.comm.impl.H1ReceiverThread;
import at.redeye.Communication.sps.H1.comm.impl.H1TCPHandling;
import at.redeye.FrameWork.base.BaseDialog;
import at.redeye.FrameWork.base.Root;
import at.redeye.FrameWork.base.Setup;

/**
 *
 * @author mmattl
 */
public class H1CommunicationManagerUI extends BaseDialog implements IH1CommListener {

    /**
     *
     */
    private static final long serialVersionUID = 1L;
    private IH1Communication h1comm = null;
    private Logger logger = Logger.getLogger(H1CommunicationManagerUI.class.getSimpleName());

    /** Creates new form H1ConnectionManagerUI */
    public H1CommunicationManagerUI(Root root) {

        super(root, "H1/TCP Kommunikationsmanager");
        h1comm = H1TCPHandling.getInstance(new H1ConnectionDefinition("", "", ""), logger);

        initComponents();

        h1comm.addListener(this);

        actionConnectionPhaseChanged(h1comm.getConnectionPhase(), " --- ");

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonTransmit = new javax.swing.JButton();
        labelToSPS = new javax.swing.JLabel();
        labelFromSPS = new javax.swing.JLabel();
        labelSPSIP = new javax.swing.JLabel();
        labelPort = new javax.swing.JLabel();
        labelRTSAP = new javax.swing.JLabel();
        labelLTSAP = new javax.swing.JLabel();
        fieldIPaddress = new javax.swing.JTextField();
        fieldPort = new javax.swing.JTextField();
        fieldLTSAP = new javax.swing.JTextField();
        fieldRTSAP = new javax.swing.JTextField();
        buttonConnect = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textareaToSPS = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        textareaFromSPS = new javax.swing.JTextArea();
        labelTitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        h1StatusDisplay1 = new at.redeye.Communication.sps.H1.widgets.H1StatusDisplay();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        buttonTransmit.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        buttonTransmit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/at/redeye/FrameWork/base/resources/icons/next.png"))); // NOI18N
        buttonTransmit.setText("Senden");
        buttonTransmit.setPreferredSize(new java.awt.Dimension(120, 30));
        buttonTransmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTransmitActionPerformed(evt);
            }
        });

        labelToSPS.setFont(new java.awt.Font("Tahoma", 0, 12));
        labelToSPS.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelToSPS.setText("An SPS (String)");

        labelFromSPS.setFont(new java.awt.Font("Tahoma", 0, 12));
        labelFromSPS.setText("Von SPS");

        labelSPSIP.setFont(new java.awt.Font("Tahoma", 0, 12));
        labelSPSIP.setText("IP-Adresse");
        labelSPSIP.setPreferredSize(new java.awt.Dimension(40, 15));

        labelPort.setFont(new java.awt.Font("Tahoma", 0, 12));
        labelPort.setText("Port");
        labelPort.setPreferredSize(new java.awt.Dimension(40, 15));

        labelRTSAP.setFont(new java.awt.Font("Tahoma", 0, 12));
        labelRTSAP.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelRTSAP.setText("R-TSAP");
        labelRTSAP.setPreferredSize(new java.awt.Dimension(40, 15));

        labelLTSAP.setFont(new java.awt.Font("Tahoma", 0, 12));
        labelLTSAP.setText("L-TSAP");

        fieldIPaddress.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        fieldIPaddress.setText(root.getSetup().getConfig(Setup.H1IPAddress, ""));
        fieldIPaddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fieldIPaddressKeyPressed(evt);
            }
        });

        fieldPort.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        fieldPort.setText(root.getSetup().getConfig(Setup.H1Port, ""));
        fieldPort.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fieldPortKeyPressed(evt);
            }
        });

        fieldLTSAP.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        fieldLTSAP.setText(root.getSetup().getConfig(Setup.H1LTSAP, ""));
        fieldLTSAP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fieldLTSAPKeyPressed(evt);
            }
        });

        fieldRTSAP.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        fieldRTSAP.setText(root.getSetup().getConfig(Setup.H1RTSAP, ""));
        fieldRTSAP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fieldRTSAPKeyPressed(evt);
            }
        });


        buttonConnect.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        buttonConnect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/at/redeye/FrameWork/base/resources/icons/player_start.png"))); // NOI18N
        buttonConnect.setText("Verbinden");
        buttonConnect.setPreferredSize(new java.awt.Dimension(120, 30));
        buttonConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonConnectActionPerformed(evt);
            }
        });

        textareaToSPS.setColumns(20);
        textareaToSPS.setLineWrap(true);
        textareaToSPS.setRows(5);
        textareaToSPS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textareaToSPSKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(textareaToSPS);

        textareaFromSPS.setColumns(20);
        textareaFromSPS.setEditable(false);
        textareaFromSPS.setLineWrap(true);
        textareaFromSPS.setRows(5);
        jScrollPane2.setViewportView(textareaFromSPS);

        labelTitle.setFont(new java.awt.Font("Tahoma", 0, 24));
        labelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitle.setText("     H1/TCP Kommunikationsmanager");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel1.setText("Status");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/at/redeye/FrameWork/base/resources/icons/fileclose.gif"))); // NOI18N
        jButton1.setText("Schließen");
        jButton1.setPreferredSize(new java.awt.Dimension(120, 30));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClose(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                    .addComponent(labelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelRTSAP, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                            .addComponent(labelLTSAP, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                            .addComponent(labelPort, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                            .addComponent(labelSPSIP, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(h1StatusDisplay1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(fieldRTSAP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                                    .addComponent(fieldLTSAP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                                    .addComponent(fieldPort, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                                    .addComponent(fieldIPaddress, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(buttonConnect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labelFromSPS, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labelToSPS, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE))
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonTransmit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitle)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSPSIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonConnect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldIPaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLTSAP)
                    .addComponent(fieldLTSAP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRTSAP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldRTSAP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(h1StatusDisplay1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelToSPS)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonTransmit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelFromSPS)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonTransmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTransmitActionPerformed

    	IH1QueueSender sender = new H1QueueSender();
        sender.transmit(textareaToSPS.getText().getBytes());
        
}//GEN-LAST:event_buttonTransmitActionPerformed

    private void buttonConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonConnectActionPerformed


        try {
            int port = (fieldPort.getText().isEmpty() ? IH1Communication.tsap_port
                    : Integer.parseInt(fieldPort.getText()));
            H1ConnectionDefinition conndef = new H1ConnectionDefinition(
                    fieldIPaddress.getText(), port, fieldLTSAP.getText(),
                    fieldRTSAP.getText());
            h1comm.setStopRequest(); // stop
            h1comm.setConnectionDefinition(conndef);
            h1comm.handleH1Request(); // start
            root.getSetup().setConfig(Setup.H1IPAddress,
                    fieldIPaddress.getText());
            root.getSetup().setConfig(Setup.H1LTSAP, fieldLTSAP.getText());
            root.getSetup().setConfig(Setup.H1RTSAP, fieldRTSAP.getText());
            root.getSetup().setConfig(Setup.H1Port, fieldPort.getText());

            // Master only
            H1ReceiverThread rec = new H1ReceiverThread(h1comm, logger);
            rec.start();



        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(this, "Die Port-Angabe muss numerisch sein!",
                    "Datenerfassung", JOptionPane.ERROR_MESSAGE);
            return;
        }



}//GEN-LAST:event_buttonConnectActionPerformed

    private void buttonClose(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonClose
        close();
    }//GEN-LAST:event_buttonClose

    private void textareaToSPSKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textareaToSPSKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            buttonTransmitActionPerformed(null);
            evt.consume();
        }
    }//GEN-LAST:event_textareaToSPSKeyPressed

    private void fieldIPaddressKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldIPaddressKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            buttonConnectActionPerformed(null);
        }
    }//GEN-LAST:event_fieldIPaddressKeyPressed

    private void fieldPortKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldPortKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            buttonConnectActionPerformed(null);
        }
    }//GEN-LAST:event_fieldPortKeyPressed

    private void fieldLTSAPKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldLTSAPKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            buttonConnectActionPerformed(null);
        }
    }//GEN-LAST:event_fieldLTSAPKeyPressed

    private void fieldRTSAPKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldRTSAPKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            buttonConnectActionPerformed(null);
        }
    }//GEN-LAST:event_fieldRTSAPKeyPressed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonConnect;
    private javax.swing.JButton buttonTransmit;
    private javax.swing.JTextField fieldIPaddress;
    private javax.swing.JTextField fieldLTSAP;
    private javax.swing.JTextField fieldPort;
    private javax.swing.JTextField fieldRTSAP;
    private at.redeye.Communication.sps.H1.widgets.H1StatusDisplay h1StatusDisplay1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelFromSPS;
    private javax.swing.JLabel labelLTSAP;
    private javax.swing.JLabel labelPort;
    private javax.swing.JLabel labelRTSAP;
    private javax.swing.JLabel labelSPSIP;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JLabel labelToSPS;
    private javax.swing.JTextArea textareaFromSPS;
    private javax.swing.JTextArea textareaToSPS;
    // End of variables declaration//GEN-END:variables

    public void actionMessageOutbound(byte [] data) {
    
    	textareaToSPS.setText("");
    	StringBuilder str = new StringBuilder();
        for (int i = 0; i < data.length; i++) {
            str.append(String.format("%02x ", data[i]));
        }
        textareaToSPS.setText(str.toString());
    }

    public void actionConnectionPhaseChanged(ConnectionPhase newPhase, String message) {

        h1StatusDisplay1.setNewPhase(newPhase);
        h1StatusDisplay1.setErrorInfo(message);


    }

    public void actionMessageInbound(byte[] data) {

        textareaFromSPS.setText("");
        StringBuilder str = new StringBuilder();
        for (int i = 0; i < data.length; i++) {
            str.append(String.format("%02x ", data[i]));
        }
        textareaFromSPS.setText(str.toString());


    }

    @Override
    public void close() {

        root.saveSetup();
        super.close();
    }
}
