/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * H1StatusDisplay.java
 *
 * Created on 27.05.2009, 11:43:01
 */
package at.redeye.Communication.sps.H1.widgets;

import at.redeye.Communication.sps.H1.comm.IH1CommListener;
import at.redeye.Communication.sps.H1.comm.impl.ConnectionPhase;
import java.awt.Color;

/**
 *
 * @author mmattl
 */
public class H1StatusDisplay extends javax.swing.JPanel implements IH1CommListener {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/** Creates new form H1StatusDisplay */
    public H1StatusDisplay() {
        initComponents();
    }

    public H1StatusDisplay(ConnectionPhase phase) {
        initComponents();
        setNewPhase(phase);
    }

    public void setNewPhase(ConnectionPhase phase) {

        fieldStatus.setText(phase.name());

        switch (phase) {
            case Disconnected: // FT
            case DisConnectionAttempt:
            case TCPConnectionAttempt: // FT
            default:
                fieldStatusLight.setBackground(Color.RED);
                break;

            case TCPConnected: // FT
            case H1ConnectionAttempt: // FT
                fieldStatusLight.setBackground(Color.ORANGE);
                break;
            case H1Connected:
                fieldStatusLight.setBackground(Color.GREEN);
                break;

        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        fieldStatus = new javax.swing.JTextField();
        fieldStatusLight = new javax.swing.JTextField();

        setName("H1StatusDisplay"); // NOI18N

        fieldStatus.setColumns(20);
        fieldStatus.setEditable(false);
        fieldStatus.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        fieldStatusLight.setColumns(2);
        fieldStatusLight.setEditable(false);
        fieldStatusLight.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(fieldStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(fieldStatusLight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldStatusLight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fieldStatus;
    private javax.swing.JTextField fieldStatusLight;
    // End of variables declaration//GEN-END:variables

    public void actionConnectionPhaseChanged(ConnectionPhase newPhase) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public void actionMessageInbound(byte[] data) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public void actionMessageOutbound() {
        throw new UnsupportedOperationException("Not supported yet.");
    }
}
