/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * H1StatusDisplay.java
 *
 * Created on 27.05.2009, 11:43:01
 */
package at.redeye.Communication.sps.H1.widgets;

import at.redeye.Communication.sps.H1.comm.impl.ConnectionPhase;
import java.awt.Color;

/**
 *
 * @author mmattl
 */
public class H1StatusDisplay extends javax.swing.JPanel  {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/** Creates new form H1StatusDisplay */
    public H1StatusDisplay() {
        initComponents();
    }

    public H1StatusDisplay(ConnectionPhase phase) {
        initComponents();
        setNewPhase(phase);
    }

    public void setNewPhase(ConnectionPhase phase) {

        fieldStatus.setText(phase.name());

        switch (phase) {
            case Disconnected: // FT
            case DisConnectionAttempt:
            case TCPConnectionAttempt: // FT
            default:
                fieldStatusLight.setBackground(Color.RED);
                break;

            case TCPConnected: // FT
            case H1ConnectionAttempt: // FT
                fieldStatusLight.setBackground(Color.ORANGE);
                break;
            case H1Connected:
                fieldStatusLight.setBackground(Color.GREEN);
                break;

        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fieldStatus = new javax.swing.JTextField();
        fieldStatusLight = new javax.swing.JTextField();
        fieldErrorInfo = new javax.swing.JTextField();

        setName("H1StatusDisplay"); // NOI18N

        fieldStatus.setColumns(20);
        fieldStatus.setEditable(false);
        fieldStatus.setFont(new java.awt.Font("Tahoma", 0, 12));

        fieldStatusLight.setColumns(2);
        fieldStatusLight.setEditable(false);
        fieldStatusLight.setFont(new java.awt.Font("Tahoma", 0, 12));

        fieldErrorInfo.setEditable(false);
        fieldErrorInfo.setFont(new java.awt.Font("Tahoma", 0, 12));
        fieldErrorInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldErrorInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(fieldErrorInfo, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fieldStatus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(fieldStatusLight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldStatusLight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(fieldErrorInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fieldErrorInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldErrorInfoActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_fieldErrorInfoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fieldErrorInfo;
    private javax.swing.JTextField fieldStatus;
    private javax.swing.JTextField fieldStatusLight;
    // End of variables declaration//GEN-END:variables

}
