/*
 * MainWin.java
 *
 * Created on 2. Januar 2009, 10:07
 */
package at.redeye.HotlineHours;

import at.redeye.FrameWork.base.BaseDialog;
import at.redeye.FrameWork.base.Root;
import at.redeye.FrameWork.base.chart.impl.CategoryChartData;
import at.redeye.FrameWork.base.prm.impl.gui.GlobalConfig;
import at.redeye.FrameWork.base.prm.impl.gui.LocalConfig;
import at.redeye.FrameWork.base.transaction.Transaction;
import at.redeye.SqlDBInterface.SqlDBIO.impl.MOMMDBDataType;
import at.redeye.SqlDBInterface.SqlDBIO.impl.UnsupportedDBDataTypeException;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author  martin
 */
public class MainWin extends BaseDialog {

    private static final long serialVersionUID = 1L;

    /** Creates new form MainWin
     * @param root
     */
    public MainWin(Root root) {
        super(root, "Bereitschaft - Stundenauswertung");
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelMonat = new javax.swing.JLabel();
        basicColumnChart = new at.redeye.FrameWork.base.chart.impl.BasicCategoryBarChart(new CategoryChartData ("Stunden / Person", "Person", "Stunden", PlotOrientation.VERTICAL, new DefaultCategoryDataset(), null));
        dBFilterMonth = new at.redeye.FrameWork.widgets.DBFilterComboBox();
        jButtonRead = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuProgram = new javax.swing.JMenu();
        jMenuItemAbout = new javax.swing.JMenuItem();
        jMenuQuit = new javax.swing.JMenuItem();
        jMUser = new javax.swing.JMenu();
        jMGlobalConfig = new javax.swing.JMenuItem();
        jMLocalConfig = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setForeground(new java.awt.Color(204, 204, 255));

        jLabelMonat.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabelMonat.setText("Monat");

        dBFilterMonth.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Jänner", "Februar", "März", "April", "Mai", "Juni", "Juli", "August", "September", "Oktober", "November", "Dezember" }));
        dBFilterMonth.setSelectedIndex(getMonthAsInt());
        dBFilterMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dBFilterMonthActionPerformed(evt);
            }
        });

        jButtonRead.setText("Lesen");
        jButtonRead.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReadActionPerformed(evt);
            }
        });

        jMenuProgram.setText("Programm");

        jMenuItemAbout.setText("Info");
        jMenuItemAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAboutActionPerformed(evt);
            }
        });
        jMenuProgram.add(jMenuItemAbout);

        jMenuQuit.setText("Beenden");
        jMenuQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuQuitActionPerformed(evt);
            }
        });
        jMenuProgram.add(jMenuQuit);

        jMenuBar1.add(jMenuProgram);

        jMUser.setText("Einstellungen");
        jMUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMUserActionPerformed(evt);
            }
        });

        jMGlobalConfig.setText("Globale Einstellungen");
        jMGlobalConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMGlobalConfigActionPerformed(evt);
            }
        });
        jMUser.add(jMGlobalConfig);

        jMLocalConfig.setText("Lokale Einstellungen");
        jMLocalConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMLocalConfigActionPerformed(evt);
            }
        });
        jMUser.add(jMLocalConfig);

        jMenuBar1.add(jMUser);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(basicColumnChart, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 597, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelMonat)
                        .addGap(56, 56, 56)
                        .addComponent(dBFilterMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 317, Short.MAX_VALUE)
                        .addComponent(jButtonRead)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMonat)
                    .addComponent(dBFilterMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRead))
                .addGap(18, 18, 18)
                .addComponent(basicColumnChart, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jMenuQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuQuitActionPerformed

    close();
}//GEN-LAST:event_jMenuQuitActionPerformed

private void jMUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMUserActionPerformed
}//GEN-LAST:event_jMUserActionPerformed

private void jMGlobalConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMGlobalConfigActionPerformed

    java.awt.EventQueue.invokeLater(new Runnable() {//GEN-LAST:event_jMGlobalConfigActionPerformed

            public void run() {
                new GlobalConfig(root).setVisible(true);
            }
        });

    }

private void jMLocalConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMLocalConfigActionPerformed

    java.awt.EventQueue.invokeLater(new Runnable() {

        public void run() {
            new LocalConfig(root).setVisible(true);
        }
    });
}//GEN-LAST:event_jMLocalConfigActionPerformed

private void jMenuItemAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAboutActionPerformed
// TODO add your handling code here:
    java.awt.EventQueue.invokeLater(new Runnable() {

        public void run() {
            new About(root).setVisible(true);
        }
    });

}//GEN-LAST:event_jMenuItemAboutActionPerformed

private void jButtonReadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReadActionPerformed

    Transaction trans = getTransaction();
    Date now = new Date();
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy");
    String year = sdf.format(now);

    Vector<MOMMDBDataType> typelist = new Vector<MOMMDBDataType>();
    typelist.add(MOMMDBDataType.DB_TYPE_LONG);
    typelist.add(MOMMDBDataType.DB_TYPE_STRING);
    typelist.add(MOMMDBDataType.DB_TYPE_STRING);
    typelist.add(MOMMDBDataType.DB_TYPE_LONG);

    logger.info("YEAR: " + year);
    String stmt = "select BEREITS.Name, PB.Vorname, PB.Nachname," +
            " ROUND (SUM (to_date(BEREITS.Bis, 'HH24:MI')+1 - " +
            " to_date(BEREITS.Von, 'HH24:MI'))*24) SUMME" +
            " from " +
            "PB inner join BEREITS ON " +
            "PB.PersonalNr = Bereits.Name" +
            " where " +
            "TO_CHAR (BEREITS.Datum, 'MM') = '" +
            month2Val(dBFilterMonth.getSelectedItem().toString()) + "'" +
            " and " +
            " TO_CHAR (BEREITS.Datum, 'YYYY') = " + "'" + year + "'" +
            " group by BEREITS.Name,  PB.Vorname, PB.Nachname " +
            " order by SUMME DESC";

    try {
        Vector<Vector<?>> res = trans.fetchColumnValue(stmt, typelist);

        DefaultCategoryDataset dataset = new DefaultCategoryDataset();

        for (int idx = 0; idx < res.size(); idx++) {
            Vector v = res.get(idx);
            for (int col = 0; col < v.size(); col++) {
                dataset.addValue((Long) v.get(3), "",
                        ((String) v.get(2)));
            }
        }

        CategoryChartData data = new CategoryChartData("Bereitschaftsstunden / Person",
                "Person", "Stunden", PlotOrientation.VERTICAL, dataset, null);

        basicColumnChart.updateDataSet(data);
    } catch (SQLException ex) {
        logger.error(ex.getMessage());
    } catch (UnsupportedDBDataTypeException ex) {
        logger.error(ex.getMessage());
    }

}//GEN-LAST:event_jButtonReadActionPerformed

private void dBFilterMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dBFilterMonthActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_dBFilterMonthActionPerformed
    private String month2Val(String month) {

        Date now = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("MM");
        String currmonth = sdf.format(now);

        if (month.equals("Jänner")) {
            return "01";
        } else if (month.equals("Februar")) {
            return "02";
        } else if (month.equals("März")) {
            return "03";
        } else if (month.equals("April")) {
            return "04";
        } else if (month.equals("Mai")) {
            return "05";
        } else if (month.equals("Juni")) {
            return "06";
        } else if (month.equals("Juli")) {
            return "07";
        } else if (month.equals("August")) {
            return "08";
        } else if (month.equals("September")) {
            return "09";
        } else if (month.equals("Oktober")) {
            return "10";
        } else if (month.equals("November")) {
            return "11";
        } else if (month.equals("Dezember")) {
            return "12";
        } else {
            return currmonth;
        }
    }

    @Override
    public void close() {
        closeNoAppExit();
        root.appExit();
    }

    @Override
    public void closeNoAppExit() {
        root.saveSetup();
        super.close();
        this.dispose();
    }

    private int getMonthAsInt() {
        Date now = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("MM");
        String currmonth = sdf.format(now);
        return Integer.parseInt(currmonth);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private at.redeye.FrameWork.base.chart.impl.BasicCategoryBarChart basicColumnChart;
    private at.redeye.FrameWork.widgets.DBFilterComboBox dBFilterMonth;
    private javax.swing.JButton jButtonRead;
    private javax.swing.JLabel jLabelMonat;
    private javax.swing.JMenuItem jMGlobalConfig;
    private javax.swing.JMenuItem jMLocalConfig;
    private javax.swing.JMenu jMUser;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemAbout;
    private javax.swing.JMenu jMenuProgram;
    private javax.swing.JMenuItem jMenuQuit;
    // End of variables declaration//GEN-END:variables
}


