/*
 * MainWin.java
 *
 * Created on 2. Januar 2009, 10:07
 */
package at.redeye.HotlineHours;

import at.redeye.FrameWork.base.BaseDialog;
import at.redeye.FrameWork.base.Root;
import at.redeye.FrameWork.base.chart.impl.CategoryChartData;
import at.redeye.FrameWork.base.transaction.Transaction;
import at.redeye.SqlDBInterface.SqlDBIO.impl.MOMMDBDataType;
import at.redeye.SqlDBInterface.SqlDBIO.impl.UnsupportedDBDataTypeException;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author  martin
 */
public class MainWin extends BaseDialog {

    private static final long serialVersionUID = 1L;

    /** Creates new form MainWin
     * @param root
     */
    public MainWin(Root root) {
        super(root, "Bereitschaft - Stundenauswertung " + Version.getVersion());
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabelMonat = new javax.swing.JLabel();
        basicColumnChart = new at.redeye.FrameWork.base.chart.impl.BasicCategoryBarChart(new CategoryChartData ("Stunden / Person", "Person", "Stunden", PlotOrientation.VERTICAL, new DefaultCategoryDataset(), null));
        dBFilterMonth = new at.redeye.FrameWork.widgets.DBFilterComboBox();
        jButtonRead = new javax.swing.JButton();
        jLabelYear = new javax.swing.JLabel();
        dBFilterYear = new at.redeye.FrameWork.widgets.DBFilterComboBox();
        jLabelModus = new javax.swing.JLabel();
        jRadioClassic = new javax.swing.JRadioButton();
        jRadioProd = new javax.swing.JRadioButton();
        jRadioSPS = new javax.swing.JRadioButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuProgram = new javax.swing.JMenu();
        jMenuQuit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setForeground(new java.awt.Color(204, 204, 255));

        jLabelMonat.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabelMonat.setText("Monat");

        dBFilterMonth.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Jänner", "Februar", "März", "April", "Mai", "Juni", "Juli", "August", "September", "Oktober", "November", "Dezember" }));
        dBFilterMonth.setSelectedIndex(getMonthAsInt()-1);
        dBFilterMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dBFilterMonthActionPerformed(evt);
            }
        });

        jButtonRead.setText("Lesen");
        jButtonRead.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReadActionPerformed(evt);
            }
        });

        jLabelYear.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabelYear.setText("Jahr");

        dBFilterYear.setModel(new javax.swing.DefaultComboBoxModel(setYearStrings()));
        dBFilterYear.setSelectedIndex(setYearStrings().length-1);

        jLabelModus.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelModus.setText("Modus");

        buttonGroup1.add(jRadioClassic);
        jRadioClassic.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioClassic.setSelected(true);
        jRadioClassic.setText("Classic");

        buttonGroup1.add(jRadioProd);
        jRadioProd.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioProd.setText("Produkt");
        jRadioProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioProdActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioSPS);
        jRadioSPS.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioSPS.setText("SPS");

        jMenuProgram.setText("Programm");

        jMenuQuit.setText("Beenden");
        jMenuQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuQuitActionPerformed(evt);
            }
        });
        jMenuProgram.add(jMenuQuit);

        jMenuBar1.add(jMenuProgram);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(basicColumnChart, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 933, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelMonat)
                            .addComponent(jLabelYear))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dBFilterYear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dBFilterMonth, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabelModus, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioClassic)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioProd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioSPS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 357, Short.MAX_VALUE)
                        .addComponent(jButtonRead)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMonat)
                    .addComponent(dBFilterMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dBFilterYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelYear)
                    .addComponent(jButtonRead)
                    .addComponent(jLabelModus)
                    .addComponent(jRadioClassic)
                    .addComponent(jRadioProd)
                    .addComponent(jRadioSPS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(basicColumnChart, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jMenuQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuQuitActionPerformed

    close();
}//GEN-LAST:event_jMenuQuitActionPerformed

    private String[] setYearStrings() {
        Date now = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy");
        int curryear = Integer.parseInt(sdf.format(now));
        String[] years = new String[]{String.valueOf(curryear - 2),
            String.valueOf(curryear - 1), String.valueOf(curryear)};
        return years;
    }

private void jButtonReadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReadActionPerformed

    Transaction trans = getTransaction();


    Vector<MOMMDBDataType> typelist = new Vector<MOMMDBDataType>();
    typelist.add(MOMMDBDataType.DB_TYPE_LONG);
    typelist.add(MOMMDBDataType.DB_TYPE_STRING);
    typelist.add(MOMMDBDataType.DB_TYPE_STRING);
    typelist.add(MOMMDBDataType.DB_TYPE_LONG);

    String table = getTable();

    String stmt;
    if (table.equalsIgnoreCase("BEREITS")) {
        stmt = "select " + table + ".Name, SD_EMPLDATAVIEW.Vorname, SD_EMPLDATAVIEW.Nachname," +
                " ROUND (SUM (to_date(" + table + ".Bis, 'HH24:MI') + " +
                "decode (sign (to_date(" + table + ".Bis, 'HH24:MI') - to_date(" + table + ".von, 'HH24:MI')), 1, 0, 1) - " +
                " to_date(" + table + ".Von, 'HH24:MI'))*24) SUMME" +
                " from " +
                "SD_EMPLDATAVIEW inner join " + table + " ON " +
                "SD_EMPLDATAVIEW.PersNr = " + table + ".Name" +
                " where " +
                "TO_CHAR (" + table + ".Datum, 'MM') = '" +
                month2Val(dBFilterMonth.getSelectedItem().toString()) + "'" +
                " and " +
                " TO_CHAR (" + table + ".Datum, 'YYYY') = " + "'" +
                dBFilterYear.getSelectedItem().toString() + "'" +
                " group by " + table + ".Name,  SD_EMPLDATAVIEW.Vorname, SD_EMPLDATAVIEW.Nachname " +
                " order by SUMME DESC";
    } else {
        stmt = "select " + table + ".UserId, SD_EMPLDATAVIEW.Vorname, SD_EMPLDATAVIEW.Nachname," +
                " ROUND (SUM (" + table + ".Bis + " +
                "decode (sign (" + table + ".Bis - " + table + ".Von),1, 0, 1) " +
                " - " + table + ".Von)*24) SUMME" +
                " from " +
                "SD_EMPLDATAVIEW inner join " + table + " ON " +
                "SD_EMPLDATAVIEW.PersNr = " + table + ".userId" +
                " where " +
                "TO_CHAR (" + table + ".Von, 'MM') = '" +
                month2Val(dBFilterMonth.getSelectedItem().toString()) + "'" +
                " and " +
                " TO_CHAR (" + table + ".Bis, 'YYYY') = " + "'" +
                dBFilterYear.getSelectedItem().toString() + "'" +
                " group by " + table + ".UserId,  SD_EMPLDATAVIEW.Vorname, SD_EMPLDATAVIEW.Nachname " +
                " order by SUMME DESC";

    }
    logger.info(stmt);
    try {
        Vector<Vector<?>> res = trans.fetchColumnValue(stmt, typelist);

        DefaultCategoryDataset dataset = new DefaultCategoryDataset();

        for (int idx = 0; idx < res.size(); idx++) {
            Vector v = res.get(idx);
            for (int col = 0; col < v.size(); col++) {
                dataset.addValue((Long) v.get(3), "",
                        ((String) v.get(2)));
            }
        }

        CategoryChartData data = new CategoryChartData("Bereitschaftsstunden / Person",
                "Person", "Stunden", PlotOrientation.VERTICAL, dataset, null);

        basicColumnChart.updateDataSet(data);
    } catch (SQLException ex) {
        logger.error(ex.getMessage());
    } catch (UnsupportedDBDataTypeException ex) {
        logger.error(ex.getMessage());
    }

}//GEN-LAST:event_jButtonReadActionPerformed

private void dBFilterMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dBFilterMonthActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_dBFilterMonthActionPerformed

    private String getTable() {

        if (jRadioClassic.isSelected()) {
            return "BEREITS";
        } else if (jRadioProd.isSelected()) {
            return "BEREITSPROD";
        } else {
            return "BEREITSSPS";
        }
    }

private void jRadioProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioProdActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_jRadioProdActionPerformed
    private String month2Val(String month) {

        Date now = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("MM");
        String currmonth = sdf.format(now);

        if (month.equals("Jänner")) {
            return "01";
        } else if (month.equals("Februar")) {
            return "02";
        } else if (month.equals("März")) {
            return "03";
        } else if (month.equals("April")) {
            return "04";
        } else if (month.equals("Mai")) {
            return "05";
        } else if (month.equals("Juni")) {
            return "06";
        } else if (month.equals("Juli")) {
            return "07";
        } else if (month.equals("August")) {
            return "08";
        } else if (month.equals("September")) {
            return "09";
        } else if (month.equals("Oktober")) {
            return "10";
        } else if (month.equals("November")) {
            return "11";
        } else if (month.equals("Dezember")) {
            return "12";
        } else {
            return currmonth;
        }
    }

    @Override
    public void close() {
        closeNoAppExit();
        root.appExit();
    }

    @Override
    public void closeNoAppExit() {
        root.saveSetup();
        super.close();
        this.dispose();
    }

    private int getMonthAsInt() {
        Date now = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("MM");
        String currmonth = sdf.format(now);
        return Integer.parseInt(currmonth);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private at.redeye.FrameWork.base.chart.impl.BasicCategoryBarChart basicColumnChart;
    private javax.swing.ButtonGroup buttonGroup1;
    private at.redeye.FrameWork.widgets.DBFilterComboBox dBFilterMonth;
    private at.redeye.FrameWork.widgets.DBFilterComboBox dBFilterYear;
    private javax.swing.JButton jButtonRead;
    private javax.swing.JLabel jLabelModus;
    private javax.swing.JLabel jLabelMonat;
    private javax.swing.JLabel jLabelYear;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuProgram;
    private javax.swing.JMenuItem jMenuQuit;
    private javax.swing.JRadioButton jRadioClassic;
    private javax.swing.JRadioButton jRadioProd;
    private javax.swing.JRadioButton jRadioSPS;
    // End of variables declaration//GEN-END:variables
}


