/*
 * TableLang.java
 *
 * Created on 13. November 2008, 21:13
 */

package at.redeye.FrameWork.base.ml;

import java.sql.SQLException;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;

import at.redeye.FrameWork.base.BaseDialog;
import at.redeye.FrameWork.base.Root;
import at.redeye.FrameWork.base.bindtypes.DBStrukt;
import at.redeye.FrameWork.base.ml.bindtypes.DBLang;
import at.redeye.FrameWork.base.tablemanipulator.TableManipulator;
import at.redeye.FrameWork.base.transaction.Transaction;
import at.redeye.SqlDBInterface.SqlDBIO.impl.TableBindingNotRegisteredException;
import at.redeye.SqlDBInterface.SqlDBIO.impl.UnsupportedDBDataTypeException;
import at.redeye.SqlDBInterface.SqlDBIO.impl.WrongBindFileFormatException;

/**
 * 
 * @author martin
 */
public class TableLang extends BaseDialog {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	TableManipulator tm;
	Vector<DBLang> langs = new Vector<DBLang>();

	/** Creates new form TableLang */
	public TableLang(Root root) {
		super(root, "Übersetzungen");
		initComponents();

		DBLang lang = new DBLang();

		tm = new TableManipulator(root, jTable1, lang);
		tm.prepareTable();
		tm.setEditable(lang.Trans, true);

		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				feed_table();
			}
		});
	}

	void feed_table() {
		try {
			tm.clear();
			langs.clear();

			Transaction trans = getTransaction();

			List<DBStrukt> res = trans.fetchTable(new DBLang(), "");

			for (DBStrukt strukt : res) {
				DBLang lang = (DBLang) strukt;

				tm.add(lang);
				langs.add(lang);
			}

		} catch (SQLException ex) {
			Logger.getLogger(TableLang.class.getName()).log(Level.SEVERE, null,
					ex);
		} catch (TableBindingNotRegisteredException ex) {
			Logger.getLogger(TableLang.class.getName()).log(Level.SEVERE, null,
					ex);
		} catch (UnsupportedDBDataTypeException ex) {
			Logger.getLogger(TableLang.class.getName()).log(Level.SEVERE, null,
					ex);
		} catch (WrongBindFileFormatException ex) {
			Logger.getLogger(TableLang.class.getName()).log(Level.SEVERE, null,
					ex);
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */

	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jScrollPane1 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();
		JBReload = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		jTable1.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null } }, new String[] { "Title 1",
						"Title 2", "Title 3", "Title 4" }));
		jScrollPane1.setViewportView(jTable1);

		JBReload.setText("Aktualisieren");
		JBReload.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				JBReloadActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup().addContainerGap()
								.addComponent(JBReload)
								.addContainerGap(534, Short.MAX_VALUE))
				.addComponent(jScrollPane1,
						javax.swing.GroupLayout.DEFAULT_SIZE, 663,
						Short.MAX_VALUE));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addComponent(jScrollPane1,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										353, Short.MAX_VALUE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(JBReload).addContainerGap()));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void JBReloadActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_JBReloadActionPerformed
	// TODO add your handling code here:
		feed_table();
	}// GEN-LAST:event_JBReloadActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton JBReload;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable jTable1;
	// End of variables declaration//GEN-END:variables

}
