/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ExportDialog.java
 *
 * Created on 14.06.2010, 21:33:25
 */

package at.redeye.Setup.dbexport;

import at.redeye.FrameWork.base.AutoMBox;
import at.redeye.FrameWork.base.BaseDialog;
import at.redeye.FrameWork.base.Root;
import at.redeye.FrameWork.utilities.StringUtils;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author martin
 */
public class ExportDialog extends BaseDialog implements ProgressListener {

    /** Creates new form ExportDialog */

    Thread exporter;
    boolean do_abort = false;
    DatabaseExport export;
    DBExImpFactory factory;

    public ExportDialog( Root root ) {
        super( root, "Datenbankexport" );
        initComponents();

        setBaseLanguage("de");

    }

    public void setExImportFactory(DBExImpFactory factory)
    {
        this.factory = factory;
    }

    public void doExport()
    {
        JFileChooser fc = new JFileChooser();

        int ret = fc.showSaveDialog(this);

        if( ret == JFileChooser.CANCEL_OPTION ||
            ret == JFileChooser.ERROR_OPTION )
        {
            close();
            return;
        }

        File file = fc.getSelectedFile();

        if( file == null )
        {
            close();
            return;
        }

        if( factory == null )
            factory = new DBExImpFactory();

        export = factory.getNewExporter(root, file.getPath() );

        export.setProgressListener(this);

        final BaseDialog dialog = this;

        exporter = new Thread() {

            @Override
            public void run()
            {
                AutoMBox mb = new AutoMBox(ExportDialog.class.getName())
                {

                    @Override
                    public void do_stuff() throws Exception {

                        export.doExport();

                        export.close();

                        if( !do_abort )
                            JOptionPane.showMessageDialog(dialog, MlM("Die Datenbank wurde erfolgreich exportiert!"));
                    }
                };

                close();
            }

        };

        exporter.start();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgress = new javax.swing.JProgressBar();
        jButtonCancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLTable = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButtonCancel.setText("Abbrechen");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jLabel1.setText("Datenbankexport:");

        jLTable.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLTable, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                    .addComponent(jProgress, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonCancel))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgress, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLTable, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonCancel)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed

        if( exporter != null )
        {
            do_abort = true;

            try {
                exporter.join(2000);
                logger.info("waited 10 seconds, thread didn't died, killing it.");

                export.close();              
                
                exporter = null;
                export = null;
            } catch( InterruptedException ex ) {
                logger.error( StringUtils.exceptionToString(ex));
            }
        }

    }//GEN-LAST:event_jButtonCancelActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JLabel jLTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JProgressBar jProgress;
    // End of variables declaration//GEN-END:variables

    synchronized public void setStage(String stage) {
        jLTable.setText(stage);
    }

    synchronized public void setOverallCounter(int count) {
        jProgress.setMaximum(count);
    }

    synchronized public void setCounter(int val) {
        jProgress.setValue(val);
    }

    synchronized public boolean canContinue() {
        return !do_abort;
    }

}
