/*
 * ImageSelect.java
 *
 * Created on 28. Juni 2009, 00:12
 */

package at.redeye.FrameWork.base.imagestorage;

import at.redeye.FrameWork.base.AutoMBox;
import at.redeye.FrameWork.base.BaseDialog;
import at.redeye.FrameWork.base.Root;
import at.redeye.FrameWork.base.imagestorage.bindtypes.DBImage;

/**
 *
 * @author  martin
 */
public class ImageSelect extends BaseDialog {

    ImageSelectListener listener;
    
    /** Creates new form ImageSelect */
    public ImageSelect( Root root ) {
        super( root, "Bilder Auswahl");
        
        initComponents();
        
        imageStorage.setParent(this);
        
        imageStorage.feed_list();
    }
    
    public void setSelectListener( ImageSelectListener listener )
    {
        this.listener = listener;
    }             

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imageStorage = new at.redeye.FrameWork.base.imagestorage.ImageStoragePanel();
        jButton1 = new javax.swing.JButton();
        jBCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/at/redeye/FrameWork/base/resources/icons/button_ok.gif"))); // NOI18N
        jButton1.setText("Auswählen");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jBCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/at/redeye/FrameWork/base/resources/icons/button_cancel.gif"))); // NOI18N
        jBCancel.setText("Abbrechen");
        jBCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imageStorage, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 176, Short.MAX_VALUE)
                        .addComponent(jBCancel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imageStorage, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jBCancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jBCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelActionPerformed
// TODO add your handling code here:
    close();
}//GEN-LAST:event_jBCancelActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
    
    new AutoMBox(getTitle()) {

        @Override
        public void do_stuff() throws Exception {
            ImageListContent ic = imageStorage.getSelectedValue();

            if (ic == null) {
                return;
            }
            if (listener == null) {
                return;
            }
            DBImage image = new DBImage();

            image.id.loadFromCopy(ic.getId());

            getTransaction().fetchTableWithPrimkey(image);

            listener.ImageSelected(image);
            close();
        }
    };
}//GEN-LAST:event_jButton1ActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private at.redeye.FrameWork.base.imagestorage.ImageStoragePanel imageStorage;
    private javax.swing.JButton jBCancel;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables

}
