/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TableTest.java
 *
 * Created on 15.05.2010, 09:33:53
 */

package at.redeye.FrameWork.base.tablemanipulator.test;

import at.redeye.FrameWork.base.LocalRoot;
import at.redeye.FrameWork.base.Root;
import at.redeye.FrameWork.base.prm.bindtypes.DBConfig;
import at.redeye.FrameWork.base.tablemanipulator.TableManipulator;
import java.util.Vector;
import org.apache.log4j.BasicConfigurator;

/**
 *
 * @author martin
 */
public class RowHeaderTest extends javax.swing.JFrame {

    /** Creates new form TableTest */
    int i;
    TableManipulator tm;

    public RowHeaderTest() {
        initComponents();

        Root root = new LocalRoot("TT");

        DBConfig config = new DBConfig();

        tm = new TableManipulator(root, table, config);

        Vector<DBConfig> data = new Vector<DBConfig>();

        for( i = 0 ; i < 10; i++ )
        {
            DBConfig c = new DBConfig();

            c.name.loadFromString(String.valueOf(i));
            c.value.loadFromString("value " + String.valueOf(i));
            c.descr.loadFromString("foobar " + String.valueOf(i));
            c.hist.setAeHist("martin");

            data.add(c);
        }

        tm.prepareTable();

        tm.addAll(data);

        tm.autoResize();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jCShowRowHeader = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table);

        jButton1.setText("New");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Del");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jCShowRowHeader.setSelected(true);
        jCShowRowHeader.setText("Show RowHeader");
        jCShowRowHeader.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCShowRowHeaderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addComponent(jCShowRowHeader)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jCShowRowHeader))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

            DBConfig c = new DBConfig();

            c.name.loadFromString(String.valueOf(i));
            c.value.loadFromString("value " + String.valueOf(i));
            c.descr.loadFromString("foobar " + String.valueOf(i));
            c.hist.setAeHist("martin");

            i++;

            tm.add(c);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        int row = tm.getSelectedRow();

        if( row != -1 )
        {
            tm.remove(row);
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jCShowRowHeaderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCShowRowHeaderActionPerformed

        tm.showRowHeader(jCShowRowHeader.isSelected());

    }//GEN-LAST:event_jCShowRowHeaderActionPerformed

    /**
    * @param args the command line RowHeaderTest
    */
    public static void main(String args[]) {

        BasicConfigurator.configure();

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RowHeaderTest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCShowRowHeader;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables

}
